name: Deploy Serverless

# on:
#   push:
#     branches:
#       - develop

# on:
#   push:
#     branches: [ feature/* ]

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Remove staging' 

jobs:
  deploy:
    name: Remove Staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Serverless Remove
      uses: serverless/github-action@master
      with:
        args: remove
      env:
        AWS_ACCESS_KEY_ID: AKIA5MCERQDGM2CPBRPB
        AWS_SECRET_ACCESS_KEY: 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